---
title: "Stats2 Project1"
author: "Rayon M"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries

library("tidyverse")
library("ggplot2")
library("GGally")
library("naniar")
library("car")

```

```{r}
# Get working directory
# getwd()

```

```{r}
# Create dataframe
AutoM <- read.csv("data1.csv")

view(AutoM)
head(AutoM)

#sum of missing values
sum(is.na(AutoM))

#count total missing values in each column of data frame
sapply(AutoM, function(x) sum(is.na(x)))

# rename variables for easier control.
new_AutoM <- AutoM %>% rename(Fuel_Type = Engine.Fuel.Type, HorsePower = Engine.HP, Cylinders = Engine.Cylinders, Transmission = Transmission.Type, Doors = Number.of.Doors, Market_Category = Market.Category, Vehicle_Size = Vehicle.Size, Vehicle_Style = Vehicle.Style, Highway_MPG = highway.MPG, City_MPG = city.mpg )

new_AutoM

# Function that shows the percentage of missing data
vis_miss(new_AutoM)


```


```{r}
# Create categorical variables within the data

new_AutoM$Make <- as.factor(new_AutoM$Make)
new_AutoM$Model <- as.factor(new_AutoM$Model)
new_AutoM$Fuel_Type <- as.factor(new_AutoM$Fuel_Type)
new_AutoM$Transmission <- as.factor(new_AutoM$Transmission)
new_AutoM$Market_Category <- as.factor(new_AutoM$Market_Category)
new_AutoM$Vehicle_Size <- as.factor(new_AutoM$Vehicle_Size)
new_AutoM$Vehicle_Style <- as.factor(new_AutoM$Vehicle_Style)
new_AutoM$Cylinders <- as.factor(new_AutoM$Cylinders)
new_AutoM$Doors <- as.factor(new_AutoM$Doors)
new_AutoM$Driven_Wheels <- as.factor(new_AutoM$Driven_Wheels)


```


```{r}

#ggpairs(AutoM, columns = 3:8)

new_AutoM %>% 
  select (MSRP, Year, HorsePower, Cylinders, Driven_Wheels, Doors, Highway_MPG, City_MPG) %>%
  ggpairs(mapping = aes())

```

```{r}
summary(new_AutoM)

```
```{r}
t(aggregate(MSRP~Cylinders, data = new_AutoM, summary))
```


```{r}
# Plotting the explanatory variables versus the response variable

par(mfrow=c(1,3))
plot(horsepower,mpg, xlab="horsepower",ylab="mpg")
new<-data.frame(horsepower=seq(30,300,.1))
lines(seq(30,300,.1),predict(lm(mpg~horsepower),newdata=new),col="red",lwd=4)

plot(as.factor(cylinders), mpg,xlab="cylinders",ylab="mpg",title="Auto Data Set",col=c(7,32,57,82,107))

plot(weight,mpg)
new2<-data.frame(weight=seq(1600,5200,1))
lines(seq(1600,5200,1),predict(lm(mpg~weight),newdata=new2),col="red",lwd=4)



```



```{r}
 # $ Make             : Factor w/ 48 levels
 # $ Model            : Factor w/ 915 levels
 # $ Year             : int
 # $ Engine.Fuel.Type : Factor w/ 11 levels
 # $ Engine.HP        : num
 # $ Engine.Cylinders : num
 # $ Transmission.Type: Factor w/ 4 levels
 # $ Driven_Wheels    : Factor w/ 4 levels 
 # $ Number.of.Doors  : num
 # $ Market.Category  : Factor w/ 72 levels
 # $ Vehicle.Size     : Factor w/ 3 levels
 # $ Vehicle.Style    : Factor w/ 16 levels
 # $ highway.MPG      : num
 # $ city.mpg         : int
 # $ Popularity       : int
 # $ MSRP             : int  

# Make Categorical Variable Summary
t(aggregate(MSRP~Make,data=car_data,summary))


```

```{r}
# Model Categorical Variable Summary
t(aggregate(MSRP~Model,data=car_data,summary))
```

```{r}
# Engine Fuel Type Categorical Variable Summary
t(aggregate(MSRP~Engine.Fuel.Type,data=car_data,summary))
```

```{r}
# Transmission Type Categorical Variable Summary
t(aggregate(MSRP~Transmission.Type,data=car_data,summary))

```

```{r}
# Driven_Wheels Categorical Variable Summary
t(aggregate(MSRP~Driven_Wheels,data=car_data,summary))

```

```{r}
# Market Category Categorical Variable Summary
t(aggregate(MSRP~Market.Category,data=car_data,summary))
```

```{r}
# Vehicle Size Categorical Variable Summary
t(aggregate(MSRP~Vehicle.Size,data=car_data,summary))
```

```{r}
# Vehicle Style Categorical Variable Summary
t(aggregate(MSRP~Vehicle.Style,data=car_data,summary))
```




```{r}

# I think we should convert Engine.Cylinders to a factor. If we do so, we see that the data set only has 3 records with 16 Cylinders. We may need to remove them when performing Cross Validation, etc.
Auto <- car_data

Auto$Engine.Cylinders <- as.factor(Auto$Engine.Cylinders)

summary(Auto)
attach(Auto)
```

# EDA Categorical
```{r}

# Plot Make with MSRP to see the distribution.
plot(Make,MSRP, xlab="Make",ylab="MSRP")
# Observed that the Make - Bugatti was higher than the other Makes. Also observed a few outliers for other vehicles. Interesting note is that if we remove the 16 cylinder vehicles it removes all the Bugattis.

# Plot Model to see its distribution against MSRP.
plot(Model,MSRP, xlab="Make",ylab="MSRP") # Observed Trends probably hold on including in the model.

# Plot Engine.Fuel.Type with MSRP to see the distribution.
plot(Engine.Fuel.Type,MSRP, xlab="Engine Fuel Type",ylab="MSRP") # Possibly correlated with Make


# Plot Engine.Cylinders with MSRP to see the distribution.
plot(Engine.Cylinders,MSRP, xlab="Engine Cylinders",ylab="MSRP") # Nice gradual increasing Trend. Will add to the model.

# Plot Transmission Type with MSRP to see the distribution.
plot(Transmission.Type,MSRP, xlab="Transmission Type",ylab="MSRP") # Slight descrease in the means. Automated Manual had the outliers. Interesting enough those were the Bugattis.


# Plot Driven Wheels with MSRP to see the distribution.
plot(Driven_Wheels,MSRP, xlab="Wheels",ylab="MSRP") # Slight descrease in the means. Automated Manual had the outliers. Interesting enough those were the Bugattis.

# Plot Market Category with MSRP to see the distribution.
plot(Market.Category,MSRP, xlab="Market Category",ylab="MSRP") # One to watch. Would start without it. However, I could see a potential for it to be included.


# Plot Vehicle Size with MSRP to see the distribution.
plot(Vehicle.Size,MSRP, xlab="Vehicle Size",ylab="MSRP") # Couple outliers: Buggati and the MayBach. Otherwise Means are pretty even.


# Plot Vehicle Style with MSRP to see the distribution.
plot(Vehicle.Style,MSRP, xlab="Vehicle Style",ylab="MSRP") # Couple outliers: Buggati and the MayBach. Otherwise Means are pretty even.



```


# EDA Numerical

```{r}
# Year
plot(Year,MSRP, xlab="Year",ylab="MSRP")
new<-data.frame(Year=seq(1990,2020,1))
lines(seq(1990,2020,1),predict(lm(MSRP~Year),newdata=new),col="red",lwd=4) # MSRP may need to be log transformed.

#Horsepower
plot(Engine.HP,MSRP, xlab="Horsepower",ylab="MSRP")
new<-data.frame(Engine.HP=seq(50,1010,1))
lines(seq(50,1010,1),predict(lm(MSRP~Engine.HP),newdata=new),col="red",lwd=4) # MSRP may need to be log Transformed to get a better pairing with Horsepower

#Number of Doors
plot(Number.of.Doors,MSRP, xlab="Number of Doors",ylab="MSRP")
new<-data.frame(Number.of.Doors=seq(1,10,1))
lines(seq(1,10,1),predict(lm(MSRP~Number.of.Doors),newdata=new),col="red",lwd=4) # Couple outliers but not needed for the model

#Highway MPG
plot(highway.MPG,MSRP, xlab="Highway Miles",ylab="MSRP")
new<-data.frame(highway.MPG=seq(0,1000,1))
lines(seq(0,1000,1),predict(lm(MSRP~highway.MPG),newdata=new),col="red",lwd=4)


#City MPG
plot(city.mpg,MSRP, xlab="City Miles",ylab="MSRP")
new<-data.frame(city.mpg=seq(0,1000,1))
lines(seq(0,1000,1),predict(lm(MSRP~city.mpg),newdata=new),col="red",lwd=4)

#Popularity
plot(Popularity,MSRP, xlab="Popularity",ylab="MSRP")
new<-data.frame(Popularity=seq(1,10000,1))
lines(seq(1,10000,1),predict(lm(MSRP~Popularity),newdata=new),col="red",lwd=4)


```

```{r}

summary(Auto)

```


# Multicollinearity

```{r}
attach(Auto)

pairs (Auto[, -c(1, 2,4,5, 7,8, 10, 11, 12, 15)])

Auto %>% 
  select (MSRP, Year, Engine.HP, Number.of.Doors, highway.MPG, city.mpg) %>%
  ggpairs(mapping = aes(color = Make), cardinality_threshold = 28)


Auto %>% 
  select (MSRP, Year, Engine.HP, Number.of.Doors, highway.MPG, city.mpg) %>%
  ggpairs(mapping = aes(color = Model), cardinality_threshold = 28)


Auto %>% 
  select (MSRP, Year, Engine.HP, Number.of.Doors, highway.MPG, city.mpg) %>%
  ggpairs(mapping = aes(color = Engine.Fuel.Type), cardinality_threshold = 28)

 # $ Make             : Factor w/ 48 levels (Include in Model)
 # $ Model            : Factor w/ 915 levels (Dont include in Model)
 # $ Engine.Fuel.Type : Factor w/ 11 levels (Include in Model
 # $ Engine.Cylinders : Factor w/ 9 levels (include in Model)
 # $ Transmission.Type: Factor w/ 4 levels (include in Model)
 # $ Driven_Wheels    : Factor w/ 4 levels (include in Model)
 # $ Market.Category  : Factor w/ 72 levels (Don't include in Model)
 # $ Vehicle.Size     : Factor w/ 3 levels (Include in Model)
 # $ Vehicle.Style    : Factor w/ 16 levels


```


```{r}
# Auto %>% 
#  select (MSRP, Make, Model ) %>%
#  ggpairs(mapping = aes())

#pairs(Auto[, c(MSRP, Make, Model)])
pairs (Auto[, -c(3,5,9,13,14,15)])

```




#VIF
```{r}
# First Pass
num.model <- lm(MSRP~Year + Engine.HP + Number.of.Doors + highway.MPG + city.mpg, data = Auto)
vif(num.model)

#Second Pass with Categorical Variables
num_Fact.model <- lm(MSRP~Year + Engine.HP + Number.of.Doors + highway.MPG + city.mpg + Make + Year + Engine.Fuel.Type + Engine.HP + Transmission.Type + Driven_Wheels + Vehicle.Size + Vehicle.Style, data = Auto)
vif(num_Fact.model)[,3]^2

#Third Pass without highway.MPG, Number.of.Doors. Potential Final Model.
num_Fact2.model <- lm(MSRP~Year + Engine.HP + city.mpg + Make + Year + Engine.Fuel.Type + Engine.HP + Transmission.Type + Driven_Wheels + Vehicle.Size + Vehicle.Style, data = Auto)
vif(num_Fact2.model)[,3]^2

# + Engine.Cylinders + Transmission.Type + Driven_Wheels + Vehicle.Size + Vehicle.Style
# Engine.cylinders caused the error: "there are aliased coefficients in the model" to occur. It's perfectly correlated to something.
# Dropping Highway.MPG from the Model 
# Dropping Number of Doors from the Model
```
#Residuals

```{r}

#Fix this to be a simple linear regression

plot(num_Fact2.model$fitted.values, num_Fact2.model$residuals,xlab="Fitted Values",ylab="Residuals")
plot(horsepower,horse.model$residuals,xlab="Horsepower",ylab="Residuals")

plot(num_Fact2.model)

write.csv(Auto, "Auto.csv")

```

# Log Transform MSRP

```{r}
my.model <- lm(log(MSRP)~Year + Engine.HP + city.mpg + Make + Year + Engine.Fuel.Type + Engine.HP + Transmission.Type + Driven_Wheels + Vehicle.Size + Vehicle.Style, data = Auto)

my.model <- lm(log(MSRP)~Year + Engine.HP + Number.of.Doors + city.mpg + Make + Model + Engine.Fuel.Type + Driven_Wheels + Market.Category + Transmission.Type, data = Auto)

my.model2 <-  lm(MSRP ~Year + Engine.HP + Engine.Cylinders + Number.of.Doors + highway.MPG + city.mpg + Make + Model +  Engine.Fuel.Type + Transmission.Type + Driven_Wheels + Market.Category + Vehicle.Size + Vehicle.Style, data = Auto)

plot(my.model$fitted.values,my.model$residuals,xlab="Fitted Values",ylab="Residuals")
#plot(horsepower,my.model$residuals,xlab="Horsepower",ylab="Residuals")
qqnorm(my.model$residuals)
qqline(my.model$residuals)


plot(my.model2$fitted.values,my.model2$residuals,xlab="Fitted Values",ylab="Residuals")
#plot(horsepower,my.model$residuals,xlab="Horsepower",ylab="Residuals")
qqnorm(my.model2$residuals)
qqline(my.model2$residuals)


```
# Test Terms in the Model

```{r}
summary(my.model)

```



```{r}
reg.fwd=regsubsets(log(MSRP)~Year + Engine.HP + city.mpg + Make + Year + Engine.Fuel.Type + Engine.HP + Transmission.Type + Driven_Wheels + Vehicle.Size + Vehicle.Style,data=Auto,method="forward",nvmax=20)

summary(reg.fwd)$adjr2
summary(reg.fwd)$rss
summary(reg.fwd)$bic

```


```{r}
par(mfrow=c(1,3))
bics<-summary(reg.fwd)$bic
plot(1:20,bics,type="l",ylab="BIC",xlab="# of predictors")
index<-which(bics==min(bics))
points(index,bics[index],col="red",pch=10)

adjr2<-summary(reg.fwd)$adjr2
plot(1:20,adjr2,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index<-which(adjr2==max(adjr2))
points(index,adjr2[index],col="red",pch=10)

rss<-summary(reg.fwd)$rss
plot(1:20,rss,type="l",ylab="train RSS",xlab="# of predictors")
index<-which(rss==min(rss))
points(index,rss[index],col="red",pch=10)


```

```{r}
summary(lm(MSRP ~ highway.MPG, data = train))[4]
summary(lm(MSRP ~ city.mpg, data = train))[4]

```



```{r}

library(tidyr)
spread(Auto, key = Market.Category, value=MSRP)
split(Auto, f = names(Auto))

split(Auto, f = Auto$Market.Category)

Auto

```





```{r}

# Collaborated with Braden to make this code.

Market_categories_to_binary <- function(df){
  
  split_categories <- str_split(string=df[,"Market.Category"], pattern=",")  
  
  
  # Get a character vector of the unique categories
  unique_categories <- unique(unlist(split_categories))
  
  # Remove N/A from unique_categories vector
  unique_categories <- unique_categories[unique_categories != "N/A"]
  
  # Remove High-Performance from unique_categories vector
  unique_categories <- unique_categories[unique_categories != "High-Performance"] 
  
  # Add all the new columns, initialized to zero
  for(category_index in 1:length(unique_categories)){
    
    category_name <- unique_categories[category_index]
    
    # Create a column of all zeros with this name
    df[,category_name] <- rep(0, nrow(df))
  }
  
  
  for(row_index in 1:length(split_categories)){
    
    categories <- split_categories[[row_index]]
    
    if("Factory Tuner" %in% categories){
      df[row_index, "Factory Tuner"] <- 1
    }
    
    if(("High-Performance" %in% categories) | ("Performance" %in% categories)){
      df[row_index, "Performance"] <- 1
    }
    
    if("Luxury" %in% categories){
      df[row_index, "Luxury"] <- 1
    }
    
    if("Flex Fuel" %in% categories){
      df[row_index, "Flex Fuel"] <- 1
    }
    
    if("Hatchback" %in% categories){
      df[row_index, "Hatchback"] <- 1
    }
    
    if("Hybrid" %in% categories){
      df[row_index, "Hybrid"] <- 1
    }
    
    if("Diesel" %in% categories){
      df[row_index, "Diesel"] <- 1
    }
    
    if("Crossover" %in% categories){
      df[row_index, "Crossover"] <- 1
    }
    
    if("Exotic" %in% categories){
      df[row_index, "Exotic"] <- 1
    }
  }
  
  return(df)
}



```

```{r}

#library(stringr)
Auto <- Market_categories_to_binary(df = Auto)


Auto$Year <- as.factor(Auto$Year)

write.csv(Auto, "New_Auto.csv")

Auto$Year

```



```{r}
#Braden Code
avg_multiple_priced_duplicates <- function(df){
  
  count <- 0
  
  # Create a copy of the dataframe to edit
  new_df <- df
  
  for(index in 1:nrow(df)){
    
    # Grab a dataframe row, which we will use to search for rows that are
    # exactly the same, other than having a different MSRP
    df_row <- df[index,]
    
    # Get a set of rows that are the same as  this one (other than different MSRP)
    filtered_data <- filter_by_example(df=df, row_example=df_row)
    
    # Check how many rows matched df_row
    num_matching_rows <- nrow(filtered_data)
    
    # If more than one (itself) matched... there are duplicates
    if(num_matching_rows > 1){
      
      # Get the rownames for the duplicates
      row_names <- rownames(filtered_data)
      
      # Grab the first row name, we will keep this one (arbitrary) and drop the others
      first_row_name <- row_names[1]
      
      # Calculate the average price for these duplicate rows
      average_price <- mean(filtered_data[,"MSRP"])
      
      # Set the MSRP for the first instance of these duplicates to the average
      new_df[rownames(new_df) == first_row_name, "MSRP"] <- average_price
      
      # Remove the rest of the duplicates
      removal_row_names <- row_names[row_names != first_row_name]
      new_df <- new_df[!(rownames(new_df) %in%removal_row_names),]
      
      # Just for keeping track of how many things we remove, in case of troubleshooting.
      count <- count + 1
      
    }
  }
  
  return(new_df)
}

# index <- in 1:nrow(Auto)
# df1_row <- Auto[]

```

```{r}
#Braden Code

filter_by_example <- function(df, row_example){
  
  filtered_df <- filter_all_columns(df=df,
                                    Make=row_example$Make, 
                                    Model=row_example$Model, 
                                    Year=row_example$Year,
                                    Engine.Fuel.Type=row_example$Engine.Fuel.Type,
                                    Engine.HP=row_example$Engine.HP,
                                    Engine.Cylinders=row_example$Engine.Cylinders,
                                    Transmission.Type=row_example$Transmission.Type,
                                    Driven_Wheels=row_example$Driven_Wheels,
                                    Number.of.Doors=row_example$Number.of.Doors,
                                    Market.Category=row_example$Market.Category,
                                    Vehicle.Size=row_example$Vehicle.Size,
                                    Vehicle.Style=row_example$Vehicle.Style,
                                    highway.MPG=row_example$highway.MPG,
                                    city.mpg=row_example$city.mpg,
                                    Popularity=row_example$Popularity)
  
  return(filtered_df)
  
}

filter_all_columns <- function(df, Make, Model, Year, Engine.Fuel.Type, Engine.HP, Engine.Cylinders, 
                               Transmission.Type, Driven_Wheels, Number.of.Doors, Market.Category, Vehicle.Size, 
                               Vehicle.Style, highway.MPG, city.mpg, Popularity){
  
  
  f1 <- df[,"Make"] == Make
  f2 <- df[,"Model"] == Model
  f3 <- df[,"Year"] == Year
  f4 <- df[,"Engine.Fuel.Type"] == Engine.Fuel.Type
  f5 <- df[,"Engine.HP"] == Engine.HP
  f6 <- df[,"Engine.Cylinders"] == Engine.Cylinders
  f7 <- df[,"Transmission.Type"] == Transmission.Type
  f8 <- df[,"Driven_Wheels"] == Driven_Wheels
  f9 <- df[,"Number.of.Doors"] == Number.of.Doors
  f10 <- df[,"Market.Category"] == Market.Category
  f11 <- df[,"Vehicle.Size"] == Vehicle.Size
  f12 <- df[,"Vehicle.Style"] == Vehicle.Style
  f13 <- df[,"highway.MPG"] == highway.MPG
  f14 <- df[,"city.mpg"] == city.mpg
  f15 <- df[,"Popularity"] == Popularity
  
  full_filter <- (f1& f2& f3 & f4 & f5 & f6 & f7 & f8 & f9 & f10 & f11 & f12 & f13 & f14 & f15)
  
  filtered_df <- df[full_filter,]
  
  return(filtered_df)
  
}


newAuto <- avg_multiple_priced_duplicates(df = Auto)
# newAuto

str(newAuto)

write.csv(newAuto, "Data.csv")
```

```{r}
car_data %>%
  select(Make, Model, MSRP) %>%
  group_by(Make) %>%
  summarize(count = n(), max = max(MSRP), min = min(MSRP)) %>%
  arrange(count)
```
```{r}
unique(Auto)

#Auto[duplicated(Auto)]
Auto %>% group_by_all() %>% filter(n()>1) %>% ungroup()

index1 <- car_data %>% add_rownames %>% group_by_at(vars(-rowname)) %>% filter(n()>1) %>% pull(rowname)
index1

deduped_Auto = Auto[index1,]
deduped_Auto 


index2 = sample(1:dim(deduped_Auto)[1],replace=F)
index2


test_validate = car_data[-index,]

Auto[-index2]

str(deduped_Auto)

Auto <- car_data

df <- Auto %>% distinct()

df



write.csv(df, "test2.csv")
```



